name: Salesforce CI/CD (Sandbox)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install Salesforce CLI (sf)
      run: npm install --global @salesforce/cli

    - name: Verify Salesforce CLI
      run: sf --version

    # --- Authenticate to Salesforce Sandbox ---
    - name: Authenticate to Sandbox
      env:
        SF_USERNAME: ${{ secrets.SF_USERNAME }}
        SF_PASSWORD: ${{ secrets.SF_PASSWORD }}
        SF_SECURITY_TOKEN: ${{ secrets.SF_SECURITY_TOKEN }}
      run: |
        echo "Authenticating to Salesforce Sandbox..."
        # use CLI interactive login for Sandbox (non-MFA)
        sf org login web --instance-url https://test.salesforce.com --set-default --alias sandbox --username "$SF_USERNAME" --password "$SF_PASSWORD$SF_SECURITY_TOKEN"

    # --- Deploy Metadata ---
    - name: Deploy to Sandbox
      run: |
        echo "Deploying to Salesforce Sandbox..."
        sf project deploy start --target-org sandbox --source-dir force-app --test-level RunLocalTests
